/* ═══════════════════════════════════════════════════
   KANTO TCG — ALL 151 GEN 1 POKÉMON
   ═══════════════════════════════════════════════════ */

const KANTO_POKEMON = [
  {id:1,  name:"Bulbasaur",  slug:"bulbasaur",  type1:"Grass",   type2:"Poison",  desc:"A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon."},
  {id:2,  name:"Ivysaur",    slug:"ivysaur",    type1:"Grass",   type2:"Poison",  desc:"When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs."},
  {id:3,  name:"Venusaur",   slug:"venusaur",   type1:"Grass",   type2:"Poison",  desc:"The flower on its back catches the sun's rays. The sap in the flower is nutrient-rich."},
  {id:4,  name:"Charmander", slug:"charmander", type1:"Fire",    type2:null,      desc:"Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail."},
  {id:5,  name:"Charmeleon", slug:"charmeleon", type1:"Fire",    type2:null,      desc:"When it swings its burning tail, it elevates the air temperature to unbearably high levels."},
  {id:6,  name:"Charizard",  slug:"charizard",  type1:"Fire",    type2:"Flying",  desc:"Spits fire hot enough to melt boulders. Known to cause forest fires unintentionally."},
  {id:7,  name:"Squirtle",   slug:"squirtle",   type1:"Water",   type2:null,      desc:"After birth, its back swells and hardens into a shell. It powerfully sprays foam from its mouth."},
  {id:8,  name:"Wartortle",  slug:"wartortle",  type1:"Water",   type2:null,      desc:"Often hides in water to stalk unwary prey. Its tail is covered with rich, thick fur."},
  {id:9,  name:"Blastoise",  slug:"blastoise",  type1:"Water",   type2:null,      desc:"A brutal Pokémon with pressurized water jets on its shell. They are used for high-speed tackles."},
  {id:10, name:"Caterpie",   slug:"caterpie",   type1:"Bug",     type2:null,      desc:"Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls."},
  {id:11, name:"Metapod",    slug:"metapod",    type1:"Bug",     type2:null,      desc:"This Pokémon is vulnerable to attack while its shell is soft, exposing its weak and tender body."},
  {id:12, name:"Butterfree", slug:"butterfree", type1:"Bug",     type2:"Flying",  desc:"In battle, it flaps its wings at great speed to release highly toxic dust into the air."},
  {id:13, name:"Weedle",     slug:"weedle",     type1:"Bug",     type2:"Poison",  desc:"Often found in forests, eating leaves. It has a sharp venomous stinger on its head."},
  {id:14, name:"Kakuna",     slug:"kakuna",     type1:"Bug",     type2:"Poison",  desc:"Almost incapable of moving, this Pokémon can only harden its shell to protect itself from predators."},
  {id:15, name:"Beedrill",   slug:"beedrill",   type1:"Bug",     type2:"Poison",  desc:"Flies at high speed and attacks using its large venomous stingers on its forelegs and tail."},
  {id:16, name:"Pidgey",     slug:"pidgey",     type1:"Normal",  type2:"Flying",  desc:"A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand."},
  {id:17, name:"Pidgeotto",  slug:"pidgeotto",  type1:"Normal",  type2:"Flying",  desc:"Very protective of its territory, this Pokémon will fiercely peck any intruder."},
  {id:18, name:"Pidgeot",    slug:"pidgeot",    type1:"Normal",  type2:"Flying",  desc:"When hunting, it skims the surface of water at high speed to pick off unwary prey such as Magikarp."},
  {id:19, name:"Rattata",    slug:"rattata",    type1:"Normal",  type2:null,      desc:"Gnaws anything with its hardened fangs. It can even chew through walls."},
  {id:20, name:"Raticate",   slug:"raticate",   type1:"Normal",  type2:null,      desc:"Its fangs are long and very sharp. They grow continuously, so it gnaws to keep them ground down."},
  {id:21, name:"Spearow",    slug:"spearow",    type1:"Normal",  type2:"Flying",  desc:"Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne."},
  {id:22, name:"Fearow",     slug:"fearow",     type1:"Normal",  type2:"Flying",  desc:"With its huge and magnificent wings, it can keep aloft without ever having to land for rest."},
  {id:23, name:"Ekans",      slug:"ekans",      type1:"Poison",  type2:null,      desc:"Moves silently and stealthily. Eats the eggs of birds, such as Spearow, whole."},
  {id:24, name:"Arbok",      slug:"arbok",      type1:"Poison",  type2:null,      desc:"It is rumored that the ferocious warning markings on its belly differ from region to region."},
  {id:25, name:"Pikachu",    slug:"pikachu",    type1:"Electric",type2:null,      desc:"When several of these Pokémon gather, their electricity can build and cause lightning storms."},
  {id:26, name:"Raichu",     slug:"raichu",     type1:"Electric",type2:null,      desc:"Its long tail serves as a ground to protect itself from its own high-voltage power."},
  {id:27, name:"Sandshrew",  slug:"sandshrew",  type1:"Ground",  type2:null,      desc:"Burrows deep underground in arid locations far from water. It only emerges to hunt for food."},
  {id:28, name:"Sandslash",  slug:"sandslash",  type1:"Ground",  type2:null,      desc:"Curls into a ball when threatened. It can roll while curled up to attack or escape."},
  {id:29, name:"Nidoran-F",  slug:"nidoran-f",  type1:"Poison",  type2:null,      desc:"Although small, its venomous barbs render this Pokémon dangerous. The female has smaller horns."},
  {id:30, name:"Nidorina",   slug:"nidorina",   type1:"Poison",  type2:null,      desc:"The female Nidoran's horn develops slowly. Prefers not to fight and spends most time foraging."},
  {id:31, name:"Nidoqueen",  slug:"nidoqueen",  type1:"Poison",  type2:"Ground",  desc:"Its body is encased in extremely hard scales. It is adept at sending foes flying with power charges."},
  {id:32, name:"Nidoran-M",  slug:"nidoran-m",  type1:"Poison",  type2:null,      desc:"Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom."},
  {id:33, name:"Nidorino",   slug:"nidorino",   type1:"Poison",  type2:null,      desc:"An aggressive Pokémon that is quick to attack. The horn on its head secretes a powerful venom."},
  {id:34, name:"Nidoking",   slug:"nidoking",   type1:"Poison",  type2:"Ground",  desc:"It uses its powerful tail in battle to smash, constrict, and then obliterate foes."},
  {id:35, name:"Clefairy",   slug:"clefairy",   type1:"Normal",  type2:null,      desc:"Its magical and cute appeal has many admirers. It is rare and found only in certain areas."},
  {id:36, name:"Clefable",   slug:"clefable",   type1:"Normal",  type2:null,      desc:"A timid fairy Pokémon that is rarely seen. It will run and hide the moment it senses people."},
  {id:37, name:"Vulpix",     slug:"vulpix",     type1:"Fire",    type2:null,      desc:"At the time of birth, it has just one tail. The tail splits from its tip as it grows older."},
  {id:38, name:"Ninetales",  slug:"ninetales",  type1:"Fire",    type2:null,      desc:"Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse."},
  {id:39, name:"Jigglypuff", slug:"jigglypuff", type1:"Normal",  type2:null,      desc:"When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep."},
  {id:40, name:"Wigglytuff", slug:"wigglytuff", type1:"Normal",  type2:null,      desc:"The rich, fluffy fur is delightful to touch. It has an enchanting, balloon-like body."},
  {id:41, name:"Zubat",      slug:"zubat",      type1:"Poison",  type2:"Flying",  desc:"Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets."},
  {id:42, name:"Golbat",     slug:"golbat",     type1:"Poison",  type2:"Flying",  desc:"Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly."},
  {id:43, name:"Oddish",     slug:"oddish",     type1:"Grass",   type2:"Poison",  desc:"During the day, it keeps its face buried in the ground. At night, it wanders absorbing moonlight."},
  {id:44, name:"Gloom",      slug:"gloom",      type1:"Grass",   type2:"Poison",  desc:"The fluid that oozes from its mouth isn't drool — it is a nectar that is used to attract prey."},
  {id:45, name:"Vileplume",  slug:"vileplume",  type1:"Grass",   type2:"Poison",  desc:"The larger its petals, the more toxic pollen it releases. With every step, the petals shake."},
  {id:46, name:"Paras",      slug:"paras",      type1:"Bug",     type2:"Grass",   desc:"Mushrooms named Tochukaso grow on its back. They grow from spores that are attached to the bug."},
  {id:47, name:"Parasect",   slug:"parasect",   type1:"Bug",     type2:"Grass",   desc:"A host Paras is taken over by the mushroom which then grows large. Moves at the mushroom's will."},
  {id:48, name:"Venonat",    slug:"venonat",    type1:"Bug",     type2:"Poison",  desc:"Lives in the shadows of tall trees where it eats insects. It is attracted by light at night."},
  {id:49, name:"Venomoth",   slug:"venomoth",   type1:"Bug",     type2:"Poison",  desc:"The dust-like scales covering its wings are color-coded to indicate the kinds of poison it has."},
  {id:50, name:"Diglett",    slug:"diglett",    type1:"Ground",  type2:null,      desc:"Lives about one yard underground where it feeds on plant roots. It sometimes appears above ground."},
  {id:51, name:"Dugtrio",    slug:"dugtrio",    type1:"Ground",  type2:null,      desc:"A team of 3 Diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground."},
  {id:52, name:"Meowth",     slug:"meowth",     type1:"Normal",  type2:null,      desc:"Adores round shiny things. It wanders the streets on a nightly basis to look for dropped loose change."},
  {id:53, name:"Persian",    slug:"persian",    type1:"Normal",  type2:null,      desc:"Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness."},
  {id:54, name:"Psyduck",    slug:"psyduck",    type1:"Water",   type2:null,      desc:"While lulling its enemies with its vacant look, this wily Pokémon will use psychokinetic powers."},
  {id:55, name:"Golduck",    slug:"golduck",    type1:"Water",   type2:null,      desc:"Often seen swimming elegantly by lake shores. It is often mistaken for a Kappa river monster."},
  {id:56, name:"Mankey",     slug:"mankey",     type1:"Fighting",type2:null,      desc:"Extremely quick to anger. It could be docile one moment then thrashing away the next instant."},
  {id:57, name:"Primeape",   slug:"primeape",   type1:"Fighting",type2:null,      desc:"Always furious and tenacious to boot. It will not abandon chasing its quarry until it catches it."},
  {id:58, name:"Growlithe",  slug:"growlithe",  type1:"Fire",    type2:null,      desc:"Very protective of its territory. It will bark and bite to repel intruders from its space."},
  {id:59, name:"Arcanine",   slug:"arcanine",   type1:"Fire",    type2:null,      desc:"A Pokémon that has been admired since the past for its beauty. It runs agilely as if on wings."},
  {id:60, name:"Poliwag",    slug:"poliwag",    type1:"Water",   type2:null,      desc:"Its skin is so thin, its internal organs are visible. The swirl pattern on its stomach is its bellybutton."},
  {id:61, name:"Poliwhirl",  slug:"poliwhirl",  type1:"Water",   type2:null,      desc:"Capable of living in or out of water. When out of water, it sweats to keep its body slimy."},
  {id:62, name:"Poliwrath",  slug:"poliwrath",  type1:"Water",   type2:"Fighting",desc:"An adept swimmer at both the front crawl and breaststroke. Easily overtakes the best human swimmers."},
  {id:63, name:"Abra",       slug:"abra",       type1:"Psychic", type2:null,      desc:"Using its ability to read minds, it will identify impending danger and teleport to safety."},
  {id:64, name:"Kadabra",    slug:"kadabra",    type1:"Psychic", type2:null,      desc:"It emits special alpha waves from its body that induce headaches just by being close by."},
  {id:65, name:"Alakazam",   slug:"alakazam",   type1:"Psychic", type2:null,      desc:"Its brain can outperform a super computer. Its intelligence quotient is said to be 5000."},
  {id:66, name:"Machop",     slug:"machop",     type1:"Fighting",type2:null,      desc:"Loves to build its muscles. It trains in all styles of martial arts to become even stronger."},
  {id:67, name:"Machoke",    slug:"machoke",    type1:"Fighting",type2:null,      desc:"Its muscular body is so powerful it must wear a power-save belt to regulate its motions."},
  {id:68, name:"Machamp",    slug:"machamp",    type1:"Fighting",type2:null,      desc:"Using its four powerful arms, it can throw 500 punches in one second. Its punches slice the air."},
  {id:69, name:"Bellsprout", slug:"bellsprout", type1:"Grass",   type2:"Poison",  desc:"A carnivorous Pokémon that traps and eats bugs. It uses its root feet to soak up needed moisture."},
  {id:70, name:"Weepinbell", slug:"weepinbell", type1:"Grass",   type2:"Poison",  desc:"It spits out Poison Powder to immobilize the enemy and then finishes it with a spray of Acid."},
  {id:71, name:"Victreebel", slug:"victreebel", type1:"Grass",   type2:"Poison",  desc:"Said to live in huge colonies deep in jungles, although no human has ever returned to verify this."},
  {id:72, name:"Tentacool",  slug:"tentacool",  type1:"Water",   type2:"Poison",  desc:"Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid."},
  {id:73, name:"Tentacruel", slug:"tentacruel", type1:"Water",   type2:"Poison",  desc:"The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey."},
  {id:74, name:"Geodude",    slug:"geodude",    type1:"Rock",    type2:"Ground",  desc:"Found in fields and mountains. Mistaking them for boulders, people often step on them."},
  {id:75, name:"Graveler",   slug:"graveler",   type1:"Rock",    type2:"Ground",  desc:"Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction."},
  {id:76, name:"Golem",      slug:"golem",      type1:"Rock",    type2:"Ground",  desc:"Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage."},
  {id:77, name:"Ponyta",     slug:"ponyta",     type1:"Fire",    type2:null,      desc:"Its hooves are 10 times harder than diamonds. It can trample anything completely flat in moments."},
  {id:78, name:"Rapidash",   slug:"rapidash",   type1:"Fire",    type2:null,      desc:"Very competitive, this Pokémon will chase anything that moves fast in hopes of racing it."},
  {id:79, name:"Slowpoke",   slug:"slowpoke",   type1:"Water",   type2:"Psychic", desc:"Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack."},
  {id:80, name:"Slowbro",    slug:"slowbro",    type1:"Water",   type2:"Psychic", desc:"The Shellder latched on its tail feeds on Slowpoke's tail while living as a pair."},
  {id:81, name:"Magnemite",  slug:"magnemite",  type1:"Electric",type2:null,      desc:"Uses anti-gravity to stay suspended. Appears without warning and uses Thunder Wave."},
  {id:82, name:"Magneton",   slug:"magneton",   type1:"Electric",type2:null,      desc:"Formed by several Magnemites linked together. It frequently appears when sunspots flare up."},
  {id:83, name:"Farfetchd",  slug:"farfetchd",  type1:"Normal",  type2:"Flying",  desc:"A Farfetch'd will never be separated from the leek stalk it holds in its wings."},
  {id:84, name:"Doduo",      slug:"doduo",      type1:"Normal",  type2:"Flying",  desc:"A bird that makes up for its poor flying with its fast foot speed. Leaves giant tracks."},
  {id:85, name:"Dodrio",     slug:"dodrio",     type1:"Normal",  type2:"Flying",  desc:"Uses its three heads to execute complex strategies. While two heads sleep, one stays awake."},
  {id:86, name:"Seel",       slug:"seel",       type1:"Water",   type2:null,      desc:"The protruding horn on its head is very hard. It is used for bashing through thick ice."},
  {id:87, name:"Dewgong",    slug:"dewgong",    type1:"Water",   type2:"Ice",     desc:"Loves to snooze on bitterly cold ice. The sight of it sleeping on a glacier was mistaken for a mermaid."},
  {id:88, name:"Grimer",     slug:"grimer",     type1:"Poison",  type2:null,      desc:"Appears in filthy areas. Thrives by sucking up polluted sludge pumped out of factories."},
  {id:89, name:"Muk",        slug:"muk",        type1:"Poison",  type2:null,      desc:"Thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison."},
  {id:90, name:"Shellder",   slug:"shellder",   type1:"Water",   type2:null,      desc:"Its hard shell repels any kind of attack. It is vulnerable only when its shell is open."},
  {id:91, name:"Cloyster",   slug:"cloyster",   type1:"Water",   type2:"Ice",     desc:"When attacked, it launches its horns in quick volleys. Its innards have never been seen."},
  {id:92, name:"Gastly",     slug:"gastly",     type1:"Ghost",   type2:"Poison",  desc:"Almost invisible, this gaseous Pokémon cloaks the target and puts it to sleep without notice."},
  {id:93, name:"Haunter",    slug:"haunter",    type1:"Ghost",   type2:"Poison",  desc:"Because of its ability to slip through block walls, it is said to be from another dimension."},
  {id:94, name:"Gengar",     slug:"gengar",     type1:"Ghost",   type2:"Poison",  desc:"Under a full moon, this Pokémon likes to mimic the shadows of people and laugh at their fright."},
  {id:95, name:"Onix",       slug:"onix",       type1:"Rock",    type2:"Ground",  desc:"As it grows, the stone portions of its body harden to become similar to black diamonds."},
  {id:96, name:"Drowzee",    slug:"drowzee",    type1:"Psychic", type2:null,      desc:"Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams."},
  {id:97, name:"Hypno",      slug:"hypno",      type1:"Psychic", type2:null,      desc:"When it locks eyes with an enemy, it will use a mix of psi moves such as Hypnosis and Confusion."},
  {id:98, name:"Krabby",     slug:"krabby",     type1:"Water",   type2:null,      desc:"Its pincers are not only powerful weapons, they are used to communicate with others of its kind."},
  {id:99, name:"Kingler",    slug:"kingler",    type1:"Water",   type2:null,      desc:"The large pincer has 10,000-horsepower of crushing strength. However, it is so heavy it is tough to aim."},
  {id:100,name:"Voltorb",    slug:"voltorb",    type1:"Electric",type2:null,      desc:"Usually found in power plants. Easily mistaken for a Poké Ball, it shocks those who try to pick it up."},
  {id:101,name:"Electrode",  slug:"electrode",  type1:"Electric",type2:null,      desc:"It explodes in response to even minor stimuli. It is feared, for it may go off at any moment."},
  {id:102,name:"Exeggcute",  slug:"exeggcute",  type1:"Grass",   type2:"Psychic", desc:"Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms."},
  {id:103,name:"Exeggutor",  slug:"exeggutor",  type1:"Grass",   type2:"Psychic", desc:"Legend has it that on rare occasions, one of its heads will drop off and continue on as an Exeggcute."},
  {id:104,name:"Cubone",     slug:"cubone",     type1:"Ground",  type2:null,      desc:"Because it never removes its skull helmet, no one has ever seen this Pokémon's real face."},
  {id:105,name:"Marowak",    slug:"marowak",    type1:"Ground",  type2:null,      desc:"The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets."},
  {id:106,name:"Hitmonlee",  slug:"hitmonlee",  type1:"Fighting",type2:null,      desc:"When in a hurry, its legs lengthen progressively. It runs smoothly with extra long strides."},
  {id:107,name:"Hitmonchan", slug:"hitmonchan", type1:"Fighting",type2:null,      desc:"While apparently doing nothing, it fires punches in lightning fast volleys impossible to see."},
  {id:108,name:"Lickitung",  slug:"lickitung",  type1:"Normal",  type2:null,      desc:"Its tongue can be extended like a chameleon's. It leaves a tingling sensation when it licks enemies."},
  {id:109,name:"Koffing",    slug:"koffing",    type1:"Poison",  type2:null,      desc:"Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning."},
  {id:110,name:"Weezing",    slug:"weezing",    type1:"Poison",  type2:null,      desc:"Where two kinds of poison gases meet, two Koffings will fuse over many years into a Weezing."},
  {id:111,name:"Rhyhorn",    slug:"rhyhorn",    type1:"Ground",  type2:"Rock",    desc:"Its massive bones are 1000 times harder than human bones. It can easily knock a trailer flying."},
  {id:112,name:"Rhydon",     slug:"rhydon",     type1:"Ground",  type2:"Rock",    desc:"Protected by an armor-like hide, it is capable of living in molten lava of 3600 degrees."},
  {id:113,name:"Chansey",    slug:"chansey",    type1:"Normal",  type2:null,      desc:"A rare and elusive Pokémon said to bring happiness to those who manage to catch it."},
  {id:114,name:"Tangela",    slug:"tangela",    type1:"Grass",   type2:null,      desc:"The whole body is swathed with wide vines similar to seaweed. Its vines shake as it walks."},
  {id:115,name:"Kangaskhan", slug:"kangaskhan", type1:"Normal",  type2:null,      desc:"The infant rarely ventures out of its mother's protective pouch until it is 3 years old."},
  {id:116,name:"Horsea",     slug:"horsea",     type1:"Water",   type2:null,      desc:"Known to shoot down flying insects with its accurate water gun. It hides among coral to sleep."},
  {id:117,name:"Seadra",     slug:"seadra",     type1:"Water",   type2:null,      desc:"Capable of swimming backwards by rapidly flapping its wing-like pectoral fins and stout tail."},
  {id:118,name:"Goldeen",    slug:"goldeen",    type1:"Water",   type2:null,      desc:"Its tail fin billows like an elegant ballgown, giving it the nickname the Water Queen."},
  {id:119,name:"Seaking",    slug:"seaking",    type1:"Water",   type2:null,      desc:"In autumn, its body becomes more fatty in preparation for winter. It then travels upstream."},
  {id:120,name:"Staryu",     slug:"staryu",     type1:"Water",   type2:null,      desc:"An enigmatic Pokémon that can merge with the night sky. The core in its center glows in many colors."},
  {id:121,name:"Starmie",    slug:"starmie",    type1:"Water",   type2:"Psychic", desc:"Its central core glows with the seven colors of the rainbow. Some people value it as a gem."},
  {id:122,name:"Mr. Mime",   slug:"mr-mime",    type1:"Psychic", type2:null,      desc:"If interrupted while miming, it will slap around the offender with its broad hands."},
  {id:123,name:"Scyther",    slug:"scyther",    type1:"Bug",     type2:"Flying",  desc:"With ninja-like agility and speed, it can create the illusion that there is more than one."},
  {id:124,name:"Jynx",       slug:"jynx",       type1:"Ice",     type2:"Psychic", desc:"It seductively wiggles its hips as it walks. It can cause people to dance in unison with it."},
  {id:125,name:"Electabuzz", slug:"electabuzz", type1:"Electric",type2:null,      desc:"Normally found near power plants, they can wander into populated areas searching for electricity."},
  {id:126,name:"Magmar",     slug:"magmar",     type1:"Fire",    type2:null,      desc:"Its body always burns with an orange glow that enables it to hide perfectly among flames."},
  {id:127,name:"Pinsir",     slug:"pinsir",     type1:"Bug",     type2:null,      desc:"If it grips an enemy with its pincers, it won't stop squeezing until the enemy is torn in half."},
  {id:128,name:"Tauros",     slug:"tauros",     type1:"Normal",  type2:null,      desc:"When it targets an enemy, it charges furiously while whipping its body with its three tails."},
  {id:129,name:"Magikarp",   slug:"magikarp",   type1:"Water",   type2:null,      desc:"In the distant past, it was somewhat stronger than the horribly weak form it has taken lately."},
  {id:130,name:"Gyarados",   slug:"gyarados",   type1:"Water",   type2:"Flying",  desc:"Once it begins to rampage, it won't stop until everything around it is destroyed."},
  {id:131,name:"Lapras",     slug:"lapras",     type1:"Water",   type2:"Ice",     desc:"A gentle soul that can read the minds of people. It can ferry people across the sea on its back."},
  {id:132,name:"Ditto",      slug:"ditto",      type1:"Normal",  type2:null,      desc:"Capable of copying an enemy's genetic code to instantly transform itself into a duplicate."},
  {id:133,name:"Eevee",      slug:"eevee",      type1:"Normal",  type2:null,      desc:"Its genetic code is irregular. It may mutate if it is exposed to radiation from element stones."},
  {id:134,name:"Vaporeon",   slug:"vaporeon",   type1:"Water",   type2:null,      desc:"So similar to water that it can melt away into any body of water to hide from enemies."},
  {id:135,name:"Jolteon",    slug:"jolteon",    type1:"Electric",type2:null,      desc:"It accumulates negative ions in the atmosphere to blast out 10,000-volt lightning bolts."},
  {id:136,name:"Flareon",    slug:"flareon",    type1:"Fire",    type2:null,      desc:"When it releases pent-up energy in one intense burst, the flames reach temps of 3,000 degrees."},
  {id:137,name:"Porygon",    slug:"porygon",    type1:"Normal",  type2:null,      desc:"A Pokémon that consists entirely of programming code. Capable of moving freely in cyberspace."},
  {id:138,name:"Omanyte",    slug:"omanyte",    type1:"Rock",    type2:"Water",   desc:"Although long thought to be extinct, in recent years it has been recovered from ancient fossils."},
  {id:139,name:"Omastar",    slug:"omastar",    type1:"Rock",    type2:"Water",   desc:"A prehistoric Pokémon that died out when its heavy shell made it impossible to catch prey."},
  {id:140,name:"Kabuto",     slug:"kabuto",     type1:"Rock",    type2:"Water",   desc:"A Pokémon that was resurrected from a fossil found in what was once the ocean floor eons ago."},
  {id:141,name:"Kabutops",   slug:"kabutops",   type1:"Rock",    type2:"Water",   desc:"Its sleek shape is perfect for swimming. It slices its foe with its claws and drains the body fluids."},
  {id:142,name:"Aerodactyl", slug:"aerodactyl", type1:"Rock",    type2:"Flying",  desc:"A ferocious, prehistoric Pokémon that goes for the enemy's throat with its serrated saw-like fangs."},
  {id:143,name:"Snorlax",    slug:"snorlax",    type1:"Normal",  type2:null,      desc:"Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful."},
  {id:144,name:"Articuno",   slug:"articuno",   type1:"Ice",     type2:"Flying",  desc:"A legendary bird Pokémon that can control ice. The flapping of its wings chills the air."},
  {id:145,name:"Zapdos",     slug:"zapdos",     type1:"Electric",type2:"Flying",  desc:"A legendary bird Pokémon that can control electricity. It usually lives in thunderclouds."},
  {id:146,name:"Moltres",    slug:"moltres",    type1:"Fire",    type2:"Flying",  desc:"Known as the legendary bird of fire. Every flap of its wings creates a brilliant flash of flames."},
  {id:147,name:"Dratini",    slug:"dratini",    type1:"Dragon",  type2:null,      desc:"Long thought to be a mythical creature, a small colony was recently discovered living underwater."},
  {id:148,name:"Dragonair",  slug:"dragonair",  type1:"Dragon",  type2:null,      desc:"A mystical Pokémon that exudes a gentle aura. Has the ability to change climate conditions."},
  {id:149,name:"Dragonite",  slug:"dragonite",  type1:"Dragon",  type2:"Flying",  desc:"An extremely rarely seen marine Pokémon. Its intelligence is said to match that of humans."},
  {id:150,name:"Mewtwo",     slug:"mewtwo",     type1:"Psychic", type2:null,      desc:"Created by a scientist after years of horrific gene-splicing experiments. The most ferocious Pokémon."},
  {id:151,name:"Mew",        slug:"mew",        type1:"Psychic", type2:null,      desc:"So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide."},
];

const TYPE_CLASSES = {
  Normal:'tt-normal', Fire:'tt-fire', Water:'tt-water', Grass:'tt-grass',
  Electric:'tt-electric', Ice:'tt-ice', Fighting:'tt-fighting', Poison:'tt-poison',
  Ground:'tt-ground', Flying:'tt-flying', Psychic:'tt-psychic', Bug:'tt-bug',
  Rock:'tt-rock', Ghost:'tt-ghost', Dragon:'tt-dragon',
};
